version: 4.0.1

environment:
  sonar_project: "NooBIT.AspNetCore.Mvc"
  sonar_organization: "noobit"
  sonar_token:
    secure: iWa2RuCudhm1QFn1k/Vu/pSi6wnMNuLmcZnXCP3sOMqKRB779uylQN9b1NQpcmRA
  nuget_token:
      secure: p8KUnSJfhKR3eFAhXJhstsGPwckT8t6Rpd2hzhlb+YFK9ld8i/c+QhWLLiVNTEDq

branches:
  only:
  - master

skip_branch_with_pr: true
skip_tags: true

max_jobs: 1
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

matrix:
  fast_finish: true

build_script:
  - cmd: dotnet tool install --global dotnet-sonarscanner
  - cmd: dotnet restore
  - cmd: dotnet sonarscanner begin /k:%sonar_project% /o:%sonar_organization% /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%sonar_token%" /d:sonar.cs.opencover.reportsPaths="%CD%\opencover.xml"
  - cmd: dotnet build NooBIT.AspNetCore.Mvc.sln -c Release /p:DebugType=Full
  - cmd: dotnet pack -c Release --no-build --include-symbols -o ..\..\artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
  - cmd: tools\OpenCover\OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test tests\NooBIT.AspNetCore.Mvc.Tests\NooBIT.AspNetCore.Mvc.Tests.csproj -c Release --no-build" -filter:"+[*]* -[*.Tests*]*" -oldStyle -register:user -output:"opencover.xml"
  - cmd: dotnet sonarscanner end /d:sonar.login="%sonar_token%"
  - cmd: dotnet nuget push artifacts\NooBIT.AspNetCore.Mvc.%APPVEYOR_BUILD_VERSION%.nupkg -k %nuget_token% -s https://www.nuget.org/api/v2/package
  - cmd: dotnet nuget push artifacts\NooBIT.AspNetCore.Mvc.Optimizations.%APPVEYOR_BUILD_VERSION%.nupkg -k %nuget_token% -s https://www.nuget.org/api/v2/package
  - cmd: dotnet nuget push artifacts\NooBIT.AspNetCore.Mvc.SimpleInjector.%APPVEYOR_BUILD_VERSION%.nupkg -k %nuget_token% -s https://www.nuget.org/api/v2/package

test: off
